### PR TITLE
feat: autoplay next (mvp)

### PR DESCRIPTION
**Pull request by andreasgangso**
https://github.com/bcc-code/bcc-media-platform/issues/330

### CODE REVIEW

**Comment by eliezerben** [comment]
I'm seeing type errors when running the app with these changes:
```
I/flutter (18946): The following _TypeError was thrown during a platform message
I/flutter (18946): callback:
I/flutter (18946): type 'int' is not a subtype of type 'List<Object?>' in type cast
I/flutter (18946):
I/flutter (18946): When the exception was thrown, this was the stack:
I/flutter (18946): #0      PlaybackEndedEvent.decode
```

```
I/flutter (18946): The following _TypeError was thrown during a platform message
I/flutter (18946): callback:
I/flutter (18946): type 'PlaybackStateChangedEvent' is not a subtype of type
I/flutter (18946): 'PlayerStateUpdateEvent?' in type cast
I/flutter (18946):
I/flutter (18946): When the exception was thrown, this was the stack:
I/flutter (18946): #0      PlaybackListenerPigeon.setup.<anonymous closure>
```

**Review by eliezerben — CHANGES_REQUESTED** [review]
I'm seeing type errors when running the app with these changes:
```
I/flutter (18946): The following _TypeError was thrown during a platform message
I/flutter (18946): callback:
I/flutter (18946): type 'int' is not a subtype of type 'List<Object?>' in type cast
I/flutter (18946):
I/flutter (18946): When the exception was thrown, this was the stack:
I/flutter (18946): #0      PlaybackEndedEvent.decode
```

```
I/flutter (18946): The following _TypeError was thrown during a platform message
I/flutter (18946): callback:
I/flutter (18946): type 'PlaybackStateChangedEvent' is not a subtype of type
I/flutter (18946): 'PlayerStateUpdateEvent?' in type cast
I/flutter (18946):
I/flutter (18946): When the exception was thrown, this was the stack:
I/flutter (18946): #0      PlaybackListenerPigeon.setup.<anonymous closure>
```

**Comment by andreasgangso** [comment]
> I'm seeing type errors when running the app with these changes:
> 
> ```
> I/flutter (18946): The following _TypeError was thrown during a platform message
> I/flutter (18946): callback:
> I/flutter (18946): type 'int' is not a subtype of type 'List<Object?>' in type cast
> I/flutter (18946):
> I/flutter (18946): When the exception was thrown, this was the stack:
> I/flutter (18946): #0      PlaybackEndedEvent.decode
> ```
> 
> ```
> I/flutter (18946): The following _TypeError was thrown during a platform message
> I/flutter (18946): callback:
> I/flutter (18946): type 'PlaybackStateChangedEvent' is not a subtype of type
> I/flutter (18946): 'PlayerStateUpdateEvent?' in type cast
> I/flutter (18946):
> I/flutter (18946): When the exception was thrown, this was the stack:
> I/flutter (18946): #0      PlaybackListenerPigeon.setup.<anonymous closure>
> ```

Did you restart the app fully after changing branch?

**Comment by eliezerben** [comment]
> > I'm seeing type errors when running the app with these changes:
> > ```
> > I/flutter (18946): The following _TypeError was thrown during a platform message
> > I/flutter (18946): callback:
> > I/flutter (18946): type 'int' is not a subtype of type 'List<Object?>' in type cast
> > I/flutter (18946):
> > I/flutter (18946): When the exception was thrown, this was the stack:
> > I/flutter (18946): #0      PlaybackEndedEvent.decode
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > I/flutter (18946): The following _TypeError was thrown during a platform message
> > I/flutter (18946): callback:
> > I/flutter (18946): type 'PlaybackStateChangedEvent' is not a subtype of type
> > I/flutter (18946): 'PlayerStateUpdateEvent?' in type cast
> > I/flutter (18946):
> > I/flutter (18946): When the exception was thrown, this was the stack:
> > I/flutter (18946): #0      PlaybackListenerPigeon.setup.<anonymous closure>
> > ```
> 
> Did you restart the app fully after changing branch?

Working fine after hard restart. 👍

**Review by eliezerben — APPROVED** [review]

**Pull request merged**
